// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: validate/validate.proto

package validate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_validate_validate_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         837932,
		Name:          "validate.tag",
		Tag:           "bytes,837932,opt,name=tag",
		Filename:      "validate/validate.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string tag = 837932;
	E_Tag = &file_validate_validate_proto_extTypes[0]
)

var File_validate_validate_proto protoreflect.FileDescriptor

const file_validate_validate_proto_rawDesc = "" +
	"\n" +
	"\x17validate/validate.proto\x12\bvalidate\x1a google/protobuf/descriptor.proto:1\n" +
	"\x03tag\x12\x1d.google.protobuf.FieldOptions\x18\xac\x923 \x01(\tR\x03tagB>Z<github.com/hyperxpizza/protoc-gen-validate/validate;validateb\x06proto3"

var file_validate_validate_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_validate_validate_proto_depIdxs = []int32{
	0, // 0: validate.tag:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_validate_proto_init() }
func file_validate_validate_proto_init() {
	if File_validate_validate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_validate_proto_rawDesc), len(file_validate_validate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_validate_validate_proto_goTypes,
		DependencyIndexes: file_validate_validate_proto_depIdxs,
		ExtensionInfos:    file_validate_validate_proto_extTypes,
	}.Build()
	File_validate_validate_proto = out.File
	file_validate_validate_proto_goTypes = nil
	file_validate_validate_proto_depIdxs = nil
}
